markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
theme: readthedocs # rtd-dropdown
site_name: OpenBlimp
nav:
- Getting Started: 
    - Blimp System Overview: getting_started/Blimp_system_overview.md
    - Preparation: getting_started/Preparation.md
    - Quick Start: getting_started/Quick_start.md
- User Tutorial:
    - Logic Flow: User_tutorial/logic_flow.md
    - Design Principle: User_tutorial/Design_principle.md
    - Build Blimp: User_tutorial/build_blimp.md
    - Build Electronics: User_tutorial/eletronics.md
    - Communication: User_tutorial/Communication.md
    - Blimp Code Setup: User_tutorial/Blimp_code_setup.md
    - User interface: User_tutorial/UserInterface.md
    - Hardware mapping: User_tutorial/HardwareMapping.md
- Developer Tutorial:
    - Development logic: developer_tutorial/Development_logic.md
    - Capability extension: developer_tutorial/Capability.md
    - Algorithm customization: developer_tutorial/Algo_custom.md
- Hardware: 
    - Hardware Introduction: Hardware_intro.md
    - Hardware Manufacture: Hardware_manufact.md
    - Basic Assembly: Basic_assembly.md
    - Sensors: Sensors.md
- Software: 
    - Manual Control: Manual_control.md
    - Autonomous Control: auto_control.md
- Demos:
    - Unit Test: Demo/Unit_tests.md
    - Flying Tests: Demo/Flying_test.md 
- Additional Information:
    - About Us: additional_info/AboutUs.md
    - Previous resources: additional_info/resources.md
    - How to contribute: additional_info/How_to_contribute.md
