theme: readthedocs # rtd-dropdown
site_name: OpenBlimp
nav:
- Getting Started: 
    - Blimp System Overview: Blimp_system_overview.md
    - Preparation: Preparation.md
- Hardware: 
    - Hardware Introduction: Hardware_intro.md
    - Hardware Manufacture: Hardware_manufact.md
    - Basic Assembly: Basic_assembly.md
    - Sensors: Sensors.md
- Software: 
    - Manual Control: Manual_control.md
    - Autonomous Control: auto_control.md
- Demos:
    - Sensors: Demo/Sensors.md
    - Unit Test: Demo/Unit_tests.md
    - Flying Tests: Demo/Flying_test.md 
- Developer Tutorial:
    - To be continue: To_be_continue.md
